// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  hero_excerpt?: string;
  content_format?: "article" | "podcast" | "video";
  hero_video_url?: string;
  hero_video_layout?: "video-card" | "video-feature";
  hero_video_caption?: string;
  hero_image_focus_x?: number;
  hero_image_focus_y?: number;
  hero_ad_mode?: "auto" | "custom" | "hidden";
  hero_ad_variant?: "auto" | "ia" | "growth" | "agencias" | "conferencias" | "catchall" | "newsletter" | "curso";
  hero_ad_eyebrow?: string;
  hero_ad_title?: string;
  hero_ad_cta?: string;
  hero_ad_url?: string;
  hero_ad_cover_label?: string;
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    posts: Post;
    project: Project;
  }
}